name: Docker Image CI ARM - Runnger_ARM

on:
  workflow_dispatch: # Agrega esta entrada para habilitar la ejecución manual
    branches: [ "master", "main" ] # Opcional: restringe las ramas donde se puede ejecutar

jobs:

  build_push_image_Runnger_ARM:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      name: Download codigo from repo
      
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        registry: docker.io
        username: ${{ secrets.USER_HUB }}
        password: ${{ secrets.PASS_HUB }}
        
    
    - name: Build and push the Docker image latest
      run: |
        docker build . --file Dockerfile --tag neytor/runner_arm && 
        docker image ls && docker push neytor/runner_arm